### DISCUSSION TITLE
Situationally disable extensions

### DISCUSSION THREAD

**Discussion by multimeric** [mkdocstrings/griffe#318] [Q&A]
I'm using the excellent `griffe_fieldz` extension. 

However in some cases I want to disable the dataclass handling. In my `mkdocs.yml` I have:
```yml
plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          extensions:
          - griffe_fieldz:
              include_inherited: true
```

However, in the markdown file, even if I set the extensions list to empty, it doesn't get disabled:
```
::: lls_core.writers.Writer
    options:
        extensions: []
```

Any ideas how I might do this?
