### ISSUE TITLE
bug: griffe doesn't render dynamic docstrings

### ISSUE THREAD

**Issue by Benjamin-T** [mkdocstrings/griffe#275]
### Description of the bug
When a docstring is constructed at runtime it is not rendered.

### To Reproduce
```python
class ClassWithStaticDocstring:
    """Static docstring"""


dynamic = "Dynamic"


class ClassWithDynamicDocstring:
    f"""{dynamic} docstring"""


class AssignedDocstring: ...


AssignedDocstring.__doc__ = ClassWithStaticDocstring.__doc__
```

### Expected behavior
I expect the docstring to be present like so:

![image](https://github.com/mkdocstrings/griffe/assets/20844540/480aab73-3e06-44ce-8835-a20c2cd5c0f3)

but it appears like this:

![image](https://github.com/mkdocstrings/griffe/assets/20844540/2348fa9b-d60e-4535-9a88-d8ddfa21db17)

### Environment information
```toml
[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.7.1"
griffe = "0.45.2"
mkdocs = "^1.6.0"
mkdocs-material = "^9.5.24"
mkdocstrings = "^0.25.1"
mkdocstrings-python = "^1.10.3"
ruamel-yaml = "^0.18.6"
pydantic-yaml = "^1.3.0"
```
