### ISSUE TITLE
bug: mkdocstrings filters option doesn't work anymore after upgrade to griffe 0.46.0

### ISSUE THREAD

**Issue by kkpattern** [mkdocstrings/griffe#294]
### Description of the bug

I don't know it's a griffe bug or the mkdocstrings's bug. After upgrade to griffe 0.46.0, the filters option doesn't work anymore. We have the filters option set to a empty list. After upgrade to griffe 0.46.0, the protected methods are no longer collected. Revert back to 0.45.3 fixed the issue.

### To Reproduce

With the following setting:
```yaml
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_source: false
            filters: []
```

Protected methods are no longer collected.

### Expected behavior

Projected methods can be collected.

### Environment information

```bash
griffe --debug-info  # | xclip -selection clipboard

```

```bash
- __System__: Linux-4.19.0-10-amd64-x86_64-with-glibc2.31
- __Python__: cpython 3.11.3 (/tmp/.venv/bin/python3)
- __Environment variables__:
- __Installed packages__:
  - `griffe` v0.46.0
```
