### ISSUE TITLE
feature: Disable the expand_wildcards

### ISSUE THREAD

**Issue by FormindMPO** [mkdocstrings/griffe#359]
### Is your feature request related to a problem? Please describe.

- I want to build a doc from a django project where i have a lot of `from module import *`
-> I know that these are not in the best practises, but it helps in importing local folder with a big __init__.py without rewrighting whole stuff

I don't want griffe to `expand_wildcards` and resolve everything, i only want him to read the files and docstrings that it have, nothing more

### Describe the solution you'd like
When commenting `self.expand_wildcards(module, external=False)` in the `def _post_load(self, module: Module, obj_path: str) -> Object | Alias:` method from `class GriffeLoader:`, i can load my project and everything works fine

Hence, would it be possible to add a parameter that states 
```python
if expand_wildcards_parameter:
        self.expand_wildcards(module, external=False)
```

### Describe alternatives you've considered

I could repair my * import modules but this is not what i want :(

### Additional context

This is my actual conf
```yaml
plugins:
  - mkdocstrings: # https://mkdocstrings.github.io/usage/#html-result-for-doc2
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            allow_inspection: false 
            heading_level: 3
            show_root_full_path: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            filters:
              - "!^(preventFromEmailBlacklisting.*)$"
            load_external_modules: false  # This disables following imports
            exclude_targets : true
```
