### ISSUE TITLE
Add support to ignore files

### ISSUE THREAD

**Issue by dmulyalin** [mkdocstrings/griffe#67]
**Is your feature request related to a problem? Please describe.**

Chances are Griffe might fail working with certain python modules files for various reasons, having capability to deliberately ignore
certain files might be helpful to instruct Griffe to skip troublesome code.

Fo example: https://github.com/mkdocstrings/griffe/issues/66

**Describe the solution you'd like**

Add support for ignore_files glob patterns list to do something like this in mkdocs.yaml:

```yaml
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_options: 
              ignore_files: 
                - path/to/foo*
                - *bar
```
